### ISSUE TITLE
octopod setup error (No such file or directory @ rb_sysopen - /Users/funkenstrahlen/Temp/testpodcast/_config.yml)

### ISSUE THREAD

**Issue by funkenstrahlen** [jekyll-octopod/jekyll-octopod#8]
I just discovered this project due to your talk on the Unsubscribe conference. I really like the idea of a jekyll based podcast site as I already use jekyll for my blog.

I tried to setup a test project, but `octopod setup` fails:

```
➜  testpodcast bundle
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies...
Using colorator 0.1
Using ffi 1.9.10
Using sass 3.4.22
Using rb-fsevent 0.9.7
Using kramdown 1.11.1
Using liquid 3.0.6
Using mercenary 0.3.6
Installing rouge 1.11.0
Using safe_yaml 1.0.4
Using bundler 1.12.3
Using rb-inotify 0.9.7
Using jekyll-sass-converter 1.4.0
Installing listen 3.0.8
Using jekyll-watch 1.4.0
Installing jekyll 3.1.6
Using jekyll-octopod 0.6.5
Bundle complete! 1 Gemfile dependency, 16 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
➜  testpodcast octopod setup
/Users/funkenstrahlen/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych.rb:471:in `initialize': No such file or directory @ rb_sysopen - /Users/funkenstrahlen/Temp/testpodcast/_config.yml (Errno::ENOENT)
    from /Users/funkenstrahlen/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych.rb:471:in `open'
    from /Users/funkenstrahlen/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych.rb:471:in `load_file'
    from /Users/funkenstrahlen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-octopod-0.6.5/bin/octopod:108:in `<top (required)>'
    from /Users/funkenstrahlen/.rbenv/versions/2.3.1/bin/octopod:23:in `load'
    from /Users/funkenstrahlen/.rbenv/versions/2.3.1/bin/octopod:23:in `<main>'
➜  testpodcast
```

**Comment by funkenstrahlen** [comment]
Oh I just see why I failed :) Never mind...
